### ISSUE TITLE
Firefox freezes tags when sync-tab-groups is enabled

### ISSUE THREAD

**Issue by christianlupus** [Morikko/sync-tab-groups#20]
Hello,

I used Sync Tab Groups only a short time but I like it very much.
Unfortunately this addon breaks my firefox installation. I use the default firefox from Ubuntu (57.0 at the moment). When I enable this addon, tabs freeze randomly after a short time of surfing in the net. The CPU load of firefox rises up to over 100% and the tab shows a "rotating circle" indicating some waiting. Later the tab is reported to be unresponsive and broken. If it starts with one tab, others will follow soon.
I have to shutdown firefox completely (which takes ages to complete) and restart to get usable again.

I do not have any clue what can trigger this, but it is happening quite regularly. Thus I need to keep the addon deactivated to keep firefox running. I have not seen any common reason for the breakdowns.

If you need further information/investigation, please tell me, what I can do.

Thank you 
Christian

**Comment by Morikko** [comment]
Are you using v0.1.5 ? 

It was a common trouble before due to too frequently bookmark back up (#14).
I exactly had the same problem, I fixed it in 0.1.5 and since I never had it any more.

**Comment by christianlupus** [comment]
This sounds reasonable. Of course an automatic sync would be nice but a workaround is at least some sort of solution.

**Comment by Morikko** [comment]
Can you try the v0.2.1 and tell me if you have still the problem: 
 * with auto save on (I hope not ^^)
 * with auto save off (normally impossible)

**Comment by christianlupus** [comment]
I just reactivated the addon v0.2.1. Let's see, if this will make any trouble. I will close the issue for now and reopen if the problem is not solved.

**Comment by christianlupus** [comment]
I enabled the addon and it had still problems. Especially on my archlinux machine I had problem. Sorry to inform you about that.
I think I have autosave enabled. Which checkbox are you referring to?

**Comment by Morikko** [comment]
> Which checkbox are you referring to?

Checkbox: Save Groups in bookmarks automatically

> Especially on my archlinux machine

Yes, I believe it is "Unix error 24 during operation open on file", caused by too many socket open on it..
It was my next question, are u on linux.

**Comment by Morikko** [comment]
Bugzilla ref: https://bugzilla.mozilla.org/show_bug.cgi?id=1421682

I also had again the problem. But since, I disabled the backup, it seems to be ok.

**Comment by Morikko** [comment]
Since v0.4.1: bookmark auto-save disabled; Next version will be totally different.
